=== mhmdelbaz4/Attendance-Management-System/xml/attendance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <!-- Definition of custom types -->
    <xs:simpleType name="mobileType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(010|011|012|015)\d{8}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="gradeType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="stateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="absent"/>
            <xs:enumeration value="attendant"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="coursesType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="js"/>
            <xs:enumeration value="c#"/>
            <xs:enumeration value="xml"/>
            <xs:enumeration value="html"/>
            <xs:enumeration value="css"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="trackType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="OS"/>
            <xs:enumeration value="PD"/>
            <xs:enumeration value="AI"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="trackIDType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="3"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="adminRole">
        <xs:restriction base="xs:string">
            <xs:enumeration value="assistant"/>
            <xs:enumeration value="manager"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Global elements -->
    <xs:element name="id" type="xs:integer"/>
    <xs:element name="trackName" type="trackType"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="email" type="emailType"/>
    <xs:element name="address" type="xs:string"/>
    <xs:element name="birthDate" type="xs:date"/>
    <xs:element name="mobileNo" type="mobileType"/>
    
    <!-- Definition of user data group -->
    <xs:group name="userData">
        <xs:sequence>
            <xs:element ref="name"/>
            <xs:element ref="address"/>
            <xs:element ref="birthDate"/>
        </xs:sequence>
    </xs:group>
    
    <!-- Definition of the XML schema -->
    <xs:element name="AttendanceSystem">
        <xs:complexType>
            <xs:sequence>
                <!-- Users -->
                <xs:element name="users">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- Students -->
                            <xs:element name="students">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="student" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="id"/>
                                                    <xs:group ref="userData"/>
                                                    <xs:element ref="email"/>
                                                    <xs:element ref="mobileNo"/>
                                                    <xs:element ref="trackName"/>
                                                    <xs:element name="courses">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="course" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="courseName" type="xs:string"/>
                                                                            <xs:element name="teacherID" type="xs:integer"/>
                                                                            <xs:element name="grade" type="gradeType"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="attendance">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="item" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="courseName" type="coursesType"/>
                                                                            <xs:element name="date" type="xs:date"/>
                                                                            <xs:element name="state" type="stateType"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!-- Teachers -->
                            <xs:element name="teachers">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="teacher" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="id"/>
                                                    <xs:group ref="userData"/>
                                                    <xs:element ref="email"/>
                                                    <xs:element ref="mobileNo"/>
                                                    <xs:element name="hiringDate" type="xs:date"/>
                                                    <xs:element name="salary" type="xs:integer"/>
                                                    <xs:element name="courses">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="courseName" type="coursesType" maxOccurs="unbounded"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="tracks">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="track" maxOccurs="3">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="trackName" type="trackType"/>
                                                                            <xs:element name="courseName" type="coursesType" maxOccurs="unbounded"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!-- Admins -->
                            <xs:element name="admins">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="admin" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="id"/>
                                                    <xs:group ref="userData"/>
                                                    <xs:element ref="email"/>
                                                    <xs:element ref="mobileNo"/>
                                                    <xs:element name="startDate" type="xs:date"/>
                                                    <xs:element name="role" type="adminRole"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="uniqueUserIDs">
                        <xs:selector xpath=".//id"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                    <xs:unique name="uniqueUserEmails">
                        <xs:selector xpath=".//email"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                    <xs:unique name="uniqueUserMobiles">
                        <xs:selector xpath=".//mobileNo"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                </xs:element>
                <!-- Tracks -->
                <xs:element name="tracks">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="track" maxOccurs="3">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="trackID" type="trackIDType"/>
                                        <xs:element name="trackName" type="trackType"/>
                                        <xs:element name="courses">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="course" maxOccurs="5">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="courseName" type="coursesType"/>
                                                                <xs:element name="teacherID" type="xs:integer"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element><!--end of courses-->
                                    </xs:sequence>
                                </xs:complexType>
                                <xs:unique name="uniqueTrackID">
                                    <xs:selector xpath="track"/>
                                    <xs:field xpath="trackID"/>
                                </xs:unique>
                                <xs:unique name="uniqueTrackName">
                                    <xs:selector xpath="track"/>
                                    <xs:field xpath="trackName"/>
                                </xs:unique><!--end of track-->
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- Define the key for teacher ID -->
        <xs:key name="teacherIDKey">
            <xs:selector xpath="users/teachers/teacher"/>
            <xs:field xpath="id"/>
        </xs:key>

        <!-- Define the key reference for teacher ID -->
        <xs:keyref name="teacherIDRef" refer="teacherIDKey">
            <xs:selector xpath="tracks/track/courses/course"/>
            <xs:field xpath="teacherID"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== mhmdelbaz4/Attendance-Management-System/Attendance Management System/attendance.xml
<?xml version="1.0" encoding="UTF-8"?>
<AttendanceSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\T.B\Desktop\Edit Schema\attendance.xsd">
	<users>
		<students>
			<student>
				<id>7</id>
				<name>hassan</name>
				<birthDate>2002-02-12</birthDate>
				<email>mo3456@gmail.com</email>
				<password>amira2345</password>
	           <mobileNo>01023412345</mobileNo>
				<trackName>OS</trackName>
				<attendance>
					<item>
						<teacherID>48</teacherID>
						<date>2020-12-01</date>
						<state>absent</state>
					</item>
					<item>
						<teacherID>5</teacherID>
						<date>2020-12-11</date>
						<state>attendant</state>
					</item>
				</attendance>
			</student>
			<student>
				<id>20</id>
				<name>mohamed</name>
				<birthDate>2002-02-12</birthDate>
				<email>amira@gmail.com</email>
				<password>amira7yf</password>
				<mobileNo>01023412376</mobileNo>
				<trackName>OS</trackName>
				<attendance>
					<item>
						<teacherID>48</teacherID>
						<date>2020-12-01</date>
						<state>absent</state>
					</item>
					<item>
						<teacherID>5</teacherID>
						<date>2020-12-11</date>
						<state>absent</state>
					</item>
				</attendance>
			</student>
		</students>
		<teachers>
			<teacher>
				<id>5</id>
				<name>mohamed</name>
				<birthDate>2002-12-02</birthDate>
				<email>hhgg323@gmail.com</email>
				<password>mohamed234</password>
				<mobileNo>01023456376</mobileNo>
				<hiringDate>2020-12-02</hiringDate>
				<salary>4000</salary>
				<tracks>
					<trackName>PD</trackName>
					<trackName>OS</trackName>
				</tracks>
			</teacher>
			<teacher>
				<id>48</id>
				<name>mohamed</name>
				<birthDate>2002-12-02</birthDate>
				<email>teacher1@gmail.com</email>
				<password>ali874</password>
				<mobileNo>01023478376</mobileNo>
				<hiringDate>2020-12-22</hiringDate>
				<salary>4000</salary>
				<!--Or under the courses element if the track is associated with a specific course:-->
				<tracks>
					<trackName>PD</trackName>
					<trackName>OS</trackName>
				</tracks>
			</teacher>
		</teachers>
		<admins>
			<admin>
				<id>6</id>
				<name>mohamed</name>
				<birthDate>2002-12-02</birthDate>
				<email>hhgg23@gmail.com</email>
				<password>ahmed764</password>
				<mobileNo>01023411245</mobileNo>
				<startDate>2020-10-11</startDate>
				<role>assistant</role>
			</admin>
			<admin>
				<id>9</id>
				<name>mohamed</name>
				<birthDate>2002-12-02</birthDate>
				<email>admin1@gmail.com</email>
				<password>hassan432</password>
				<mobileNo>01063412376</mobileNo>
				<startDate>2020-10-11</startDate>
				<role>manager</role>
			</admin>
		</admins>
	</users>
	<tracks>
		<track>
			<trackName>OS</trackName>
			<teachers>
				<teacherID>5</teacherID>
				<teacherID>48</teacherID>
			</teachers>
		</track>
		<track>
			<trackName>PD</trackName>
			<teachers>
				<teacherID>5</teacherID>
				<teacherID>48</teacherID>
			</teachers>
		</track>
	</tracks>
</AttendanceSystem>
